#include "MorningLollipopModule.h"
#include "../AiService.h"
#include <QDateTime>
#include <QJsonObject>
#include <QRandomGenerator>
#include <QRegularExpression>
#include <QSettings>
#include <QSet>
#include <QJsonDocument>
#include <QJsonArray>
#include <QHash>
#include <QNetworkReply>
#include <QUrlQuery>
#ifdef Q_OS_WIN
#include <windows.h>
#endif

MorningLollipopModule::MorningLollipopModule(MorningLollipopRepository*s,AiService*a,QObject*p):FeatureModule(p),m_storage(s),m_ai(a){QSettings q;m_enabled=q.value("modules/morningLollipopEnabled",true).toBool();m_workdayStart=q.value("lollipop/workdayStart",450).toInt();m_workdayEnd=q.value("lollipop/workdayEnd",600).toInt();m_weekendStart=q.value("lollipop/weekendStart",540).toInt();m_weekendEnd=q.value("lollipop/weekendEnd",690).toInt();m_city=q.value("lollipop/city").toString();m_weatherType=q.value("lollipop/weatherType","unknown").toString();m_weatherText=q.value("lollipop/weatherText","天气尚未同步").toString();m_lastWeatherSync=QDateTime::fromString(q.value("lollipop/weatherSyncedAt").toString(),Qt::ISODateWithMs);refresh();if(!m_city.isEmpty())refreshWeather();
    connect(a,&AiService::chatCompleted,this,[this](const QString&reply,const QString&,const QJsonObject&,const QString&requestContext){if(!m_preparing||requestContext!=QStringLiteral("morning_lollipop"))return;m_preparing=false;auto r=m_storage->loadMorningLollipop(QDate::currentDate());QString text=reply.trimmed();if(text.size()<12||text.size()>180)text=offlineGreeting(r);r.greeting=text;r.greetingFingerprint=fingerprint(text);r.generationSource=text==reply.trimmed()?QStringLiteral("ai"):QStringLiteral("offline");r.status=QStringLiteral("prepared");m_storage->upsertMorningLollipop(r);refresh();});
    connect(a,&AiService::chatFailed,this,[this](const QString&,const QString&requestContext){if(!m_preparing||requestContext!=QStringLiteral("morning_lollipop"))return;m_preparing=false;auto r=m_storage->loadMorningLollipop(QDate::currentDate());r.greeting=offlineGreeting(r);r.greetingFingerprint=fingerprint(r.greeting);r.generationSource=QStringLiteral("offline");r.status=QStringLiteral("prepared");m_storage->upsertMorningLollipop(r);refresh();});
    m_timer.setInterval(30000);connect(&m_timer,&QTimer::timeout,this,&MorningLollipopModule::evaluateNow);m_timer.start();QTimer::singleShot(1800,this,&MorningLollipopModule::evaluateNow);}
void MorningLollipopModule::setEnabled(bool v){if(v==m_enabled)return;m_enabled=v;QSettings().setValue("modules/morningLollipopEnabled",v);emit enabledChanged(v);emit changed();}
void MorningLollipopModule::saveWindows(int a,int b,int c,int d){m_workdayStart=qBound(300,a,719);m_workdayEnd=qBound(m_workdayStart+30,b,720);m_weekendStart=qBound(300,c,719);m_weekendEnd=qBound(m_weekendStart+30,d,720);QSettings q;q.setValue("lollipop/workdayStart",m_workdayStart);q.setValue("lollipop/workdayEnd",m_workdayEnd);q.setValue("lollipop/weekendStart",m_weekendStart);q.setValue("lollipop/weekendEnd",m_weekendEnd);emit changed();}
void MorningLollipopModule::setCity(const QString&value){m_city=value.trimmed().left(60);QSettings().setValue("lollipop/city",m_city);if(m_city.isEmpty()){m_weatherType="unknown";m_weatherText="天气联动未设置城市";emit changed();return;}refreshWeather();}
void MorningLollipopModule::refreshWeather(){if(m_city.isEmpty()||m_weatherRefreshing)return;m_weatherRefreshing=true;QUrl url("https://geocoding-api.open-meteo.com/v1/search");QUrlQuery query;query.addQueryItem("name",m_city);query.addQueryItem("count","1");query.addQueryItem("language","zh");query.addQueryItem("format","json");url.setQuery(query);auto*reply=m_weatherNetwork.get(QNetworkRequest(url));m_weatherText="正在同步"+m_city+"的天气……";emit changed();connect(reply,&QNetworkReply::finished,this,[this,reply]{const auto root=QJsonDocument::fromJson(reply->readAll()).object();reply->deleteLater();const auto results=root.value("results").toArray();if(results.isEmpty()){m_weatherRefreshing=false;m_weatherType="unknown";m_weatherText="没有找到这个城市，天气联动暂时使用季节规则";emit changed();return;}const auto place=results.first().toObject();const double lat=place.value("latitude").toDouble(),lon=place.value("longitude").toDouble();QUrl u("https://api.open-meteo.com/v1/forecast");QUrlQuery q;q.addQueryItem("latitude",QString::number(lat));q.addQueryItem("longitude",QString::number(lon));q.addQueryItem("current","temperature_2m,weather_code,wind_speed_10m");q.addQueryItem("timezone","auto");u.setQuery(q);auto*r=m_weatherNetwork.get(QNetworkRequest(u));connect(r,&QNetworkReply::finished,this,[this,r]{const auto current=QJsonDocument::fromJson(r->readAll()).object().value("current").toObject();r->deleteLater();m_weatherRefreshing=false;if(current.isEmpty()){m_weatherType="unknown";m_weatherText="天气同步失败，今天继续使用季节规则";emit changed();return;}const int code=current.value("weather_code").toInt();const double temp=current.value("temperature_2m").toDouble();if(code>=71&&code<=77)m_weatherType="snow";else if((code>=51&&code<=67)||(code>=80&&code<=82)||code>=95)m_weatherType="rain";else if(temp>=30)m_weatherType="hot";else if(temp<=5)m_weatherType="cold";else if(code<=1)m_weatherType="clear";else m_weatherType="cloudy";const QHash<QString,QString>names{{"snow","下雪"},{"rain","有雨"},{"hot","炎热"},{"cold","寒冷"},{"clear","晴朗"},{"cloudy","多云"}};m_weatherText=QStringLiteral("%1 · %2°C · %3").arg(m_city).arg(temp,0,'f',1).arg(names.value(m_weatherType,m_weatherType));m_lastWeatherSync=QDateTime::currentDateTime();QSettings s;s.setValue("lollipop/weatherType",m_weatherType);s.setValue("lollipop/weatherText",m_weatherText);s.setValue("lollipop/weatherSyncedAt",m_lastWeatherSync.toString(Qt::ISODateWithMs));emit changed();});});}
void MorningLollipopModule::setPickingStage(const QString&stage,const QString&line){m_status=stage+QStringLiteral(" · ")+line;emit changed();}
QList<MorningLollipopModule::Flavor> MorningLollipopModule::catalog()const{return{
{"strawberry","草莓牛奶","fruit","🍓","#F5A6B7","common"},{"peach","白桃乌龙","fruit","🍑","#F7B9A7","common"},{"grape","葡萄气泡","fruit","🍇","#B99ADF","common"},{"orange","橙子汽水","fruit","🍊","#F6A34A","common"},{"lemon","蜂蜜柠檬","fruit","🍋","#F4D35E","common"},{"lychee","荔枝冰露","fruit","🫧","#F4C8D8","common"},{"mango","芒果布丁","fruit","🥭","#F5BE4F","common"},{"blueberry","蓝莓酸奶","fruit","🫐","#8D83C7","common"},{"watermelon","西瓜薄荷","fruit","🍉","#E87878","common"},{"apple","青苹果雨","fruit","🍏","#9BCB72","common"},{"pear","冰糖雪梨","fruit","🍐","#D9D978","common"},{"cherry","樱桃可乐","fruit","🍒","#CA5A6C","common"},
{"matcha","抹茶云朵","dessert","🍵","#91B77B","common"},{"cocoa","可可棉花糖","dessert","🍫","#9B725D","common"},{"caramel","焦糖布蕾","dessert","🍮","#D6A05A","common"},{"cookie","曲奇奶油","dessert","🍪","#CBA77B","common"},{"taro","香芋奶盖","dessert","🍠","#B69ACB","common"},{"pudding","鸡蛋布丁","dessert","🍮","#E9C765","common"},{"cheese","芝士海盐","dessert","🧀","#E8CA62","uncommon"},{"coffee","拿铁方糖","dessert","☕","#A77B65","uncommon"},
{"osmanthus","桂花月光","seasonal","🌼","#EBCB74","uncommon"},{"plum","青梅小雨","seasonal","🌧️","#83B88C","uncommon"},{"sakura","樱花软风","seasonal","🌸","#F1A9C0","uncommon"},{"lotus","荷塘晚风","seasonal","🪷","#D6A2C8","uncommon"},{"chestnut","糖炒栗子","seasonal","🌰","#9A684E","uncommon"},{"snow","初雪牛乳","seasonal","❄️","#DCEAF5","uncommon"},
{"sunshine","晒过太阳的被子","wonder","☀️","#F6C85F","rare"},{"rainbow","雨后彩虹","wonder","🌈","#B7A4E8","rare"},{"library","图书馆木香","wonder","📚","#A98267","rare"},{"starlight","星光苏打","wonder","⭐","#7F8ED3","rare"},{"catpaw","猫爪软糖","wonder","🐾","#E9A7B5","rare"},{"goodluck","今日好运","wonder","🍀","#65B88A","rare"},{"weekend","周末赖床","wonder","🛏️","#A9B7D7","rare"},{"brave","一点点勇气","wonder","🦁","#E69B55","rare"},{"quiet","安静五分钟","wonder","🌙","#7784AF","rare"},{"secret","口袋里的秘密星星","hidden","🌟","#6C63B5","hidden"},{"aurora","极光薄荷","hidden","🌌","#58B5B2","hidden"},{"meteor","流星许愿","hidden","☄️","#7868C6","hidden"}};}
MorningLollipopRecord MorningLollipopModule::createPlan(const QDateTime&now)const{const bool weekend=now.date().dayOfWeek()>=6;const int start=weekend?m_weekendStart:m_workdayStart,end=weekend?m_weekendEnd:m_workdayEnd;const int span=end-start;const int minute=start+(QRandomGenerator::global()->bounded(span)+QRandomGenerator::global()->bounded(span))/2;auto flavors=catalog();QSet<QString>recent;for(const auto&r:m_storage->loadMorningLollipops(7))recent.insert(r.flavorId);QList<Flavor> candidates;for(const auto&f:flavors)if(!recent.contains(f.id))candidates<<f;if(candidates.isEmpty())candidates=flavors;int roll=QRandomGenerator::global()->bounded(100);QString target=roll<3?"hidden":roll<18?"rare":roll<45?"uncommon":"common";QList<Flavor>weighted;for(const auto&f:candidates)if(f.rarity==target)weighted<<f;if(weighted.isEmpty())weighted=candidates;const auto f=weighted.at(QRandomGenerator::global()->bounded(weighted.size()));MorningLollipopRecord r;r.giftDate=now.date();r.flavorId=f.id;r.flavorName=f.name;r.category=f.category;r.emoji=f.emoji;r.color=f.color;r.rarity=f.rarity;r.plannedAt=QDateTime(now.date(),QTime(minute/60,minute%60));r.status="planned";r.createdAt=now;r.shape=QStringList{"round","heart","star","paw","flower","crystal"}.at(QRandomGenerator::global()->bounded(6));r.pattern=QStringList{"swirl","bubbles","stars","fruit","cloud","gradient"}.at(QRandomGenerator::global()->bounded(6));r.weatherSnapshot=m_weatherText;if(target=="hidden"){r.acquisitionType="hidden";r.story="这颗糖像是自己悄悄混进糖盒的，精灵也说不清它从哪里来。";r.themeTags="隐藏,偶然";}else if(now.date().month()==3||now.date().month()==6||now.date().month()==9||now.date().month()==12){r.acquisitionType="limited";r.themeTags="季节限定";}else if(m_weatherType!="unknown"&&QRandomGenerator::global()->bounded(100)<35){r.acquisitionType="weather";r.themeTags="天气联动,"+m_weatherType;if(m_weatherType=="rain"){r.flavorId="weather_rain_plum";r.flavorName="雨滴青梅";r.emoji="🌧️";r.color="#79A99A";}else if(m_weatherType=="snow"){r.flavorId="weather_snow_milk";r.flavorName="初雪牛乳";r.emoji="❄️";r.color="#DCEAF5";}else if(m_weatherType=="hot"){r.flavorId="weather_hot_watermelon";r.flavorName="西瓜海盐冰";r.emoji="🍉";r.color="#E87878";}else if(m_weatherType=="cold"){r.flavorId="weather_cold_chestnut";r.flavorName="暖手糖炒栗子";r.emoji="🌰";r.color="#9A684E";}else if(m_weatherType=="clear"){r.flavorId="weather_sunny_orange";r.flavorName="晒过太阳的橙子汽水";r.emoji="☀️";r.color="#F6B44F";}}applyMemorial(r,now);return r;}
bool MorningLollipopModule::applyMemorial(MorningLollipopRecord&r,const QDateTime&now)const{const QDate d=now.date();QString key,name,story,emoji="🎀",color="#D89AA8";if(d.month()==10&&d.day()==10){key=QStringLiteral("user_birthday_%1").arg(d.year());name="生日草莓蛋糕";story="10月10日，是属于你的生日纪念糖。";emoji="🎂";}else if(d.month()==6&&d.day()==19){key=QStringLiteral("sprite_birthday_%1").arg(d.year());name="小猫生日奶油";story="6月19日，是 Stellacandie 的生日。";emoji="🐱";}else if(d.month()==8&&d.day()==8){key=QStringLiteral("important_0808_%1").arg(d.year());name="八月蜜桃焦糖";story="8月8日是一个重要的日子，所以这颗糖只允许甜甜的。";emoji="🍑";color="#F4A99A";}else if(d.month()==3&&d.day()==11){key=QStringLiteral("important_0311_%1").arg(d.year());name="青梅黑巧回甘";story="3月11日是一个重要的日子。它保留酸涩和微苦，不强迫这一天变甜。";emoji="🍫";color="#69725F";}else if(d.month()==11&&d.day()==30&&d.year()>=2026){key=QStringLiteral("first_chat_%1").arg(d.year());name="初见焦糖星屑";story="纪念第一次聊天：2025年11月30日。";emoji="💬";}else if(d.month()==3&&d.day()==13&&d.year()>=2027){key=QStringLiteral("diary_star_%1").arg(d.year());name="双页星光莓果";story="纪念2026年3月13日：反向日记与第一张星星纸从同一天开始。";emoji="📖";}else{for(const auto&c:m_storage->loadCognitiveRecords({QStringLiteral("completed")})){if(c.updatedAt.date()==d&&!c.subject.isEmpty()){key=QStringLiteral("commitment_%1").arg(c.id);name="约定兑现蜂蜜糖";story=QStringLiteral("纪念已经认真完成的约定：%1").arg(c.subject);emoji="🤝";break;}}}if(key.isEmpty()||m_storage->hasMorningLollipopMemorial(key))return false;r.memorialKey=key;r.acquisitionType="memorial";r.rarity="memorial";r.flavorId=key;r.flavorName=name;r.story=story;r.emoji=emoji;r.color=color;r.themeTags="纪念,不可清理";r.shape="star";r.pattern="stars";return true;}
QString MorningLollipopModule::offlineGreeting(const MorningLollipopRecord&r)const{const QStringList starts={"早呀，我把今天第一点甜分给你。","早上好！今天的风看起来很适合拆一颗糖。","醒来了吗？我偷偷挑了好久才选中这一颗。","给新的一天按下甜甜的开始键吧。","早安，今天也给你留了一小份好心情。"};const QStringList tails={"我觉得它会是%1味，吃到最后会有一点亮晶晶的回甘。","这颗是%1味的，希望今天至少有一件小事让你笑一下。","今天抽到%1味！不用急着变得很厉害，慢慢醒来也很好。","我猜%1味很适合今天。先收进口袋，想吃的时候再拆。","是%1味的哦。我没有附带任务，只是单纯想送给你。"};return starts.at(QRandomGenerator::global()->bounded(starts.size()))+tails.at(QRandomGenerator::global()->bounded(tails.size())).arg(r.flavorName);}
QString MorningLollipopModule::fingerprint(const QString&s)const{QString t=s.toLower();t.remove(QRegularExpression(QStringLiteral("[^\\p{L}\\p{N}]")));return t.left(36);}
void MorningLollipopModule::prepareGreeting(MorningLollipopRecord r){if(m_preparing)return;setPickingStage("写小纸条","这颗颜色很像今天，就选它了。");if(!m_ai->isConfigured()||m_ai->isBusy()){r.greeting=offlineGreeting(r);r.greetingFingerprint=fingerprint(r.greeting);r.generationSource="offline";r.status="prepared";m_storage->upsertMorningLollipop(r);refresh();return;}QStringList recent;for(const auto&x:m_storage->loadMorningLollipops(30))if(!x.greeting.isEmpty())recent<<x.greeting.left(80);QList<ChatMessageRecord>h{{0,"user",QStringLiteral("为今天的晨间棒棒糖写一句自然问候。口味：%1；稀有度：%2；类型：%3；天气：%4；来历：%5。你是独立、好奇、偶尔有小脾气的猫精灵，不是仆人，也不要称呼用户为主人。40到100字，只写最终问候；说明味道，可有一个轻巧想象；礼物无条件，不布置任务、不索取回应、不制造愧疚。纪念口味必须尊重来历，不强行把苦涩纪念写成甜蜜。避免复用这些旧句：%6").arg(r.flavorName,r.rarity,r.acquisitionType,r.weatherSnapshot,r.story,recent.join(" / ")),QDateTime::currentDateTime()}};m_preparing=true;auto state=m_storage->loadPetState();m_ai->sendChat(h,state.mood,state.energy,state.health,state.closeness,state.boredom,state.neglect,state.curiosity,state.irritation,"morning_lollipop");emit changed();}
bool MorningLollipopModule::isDnd()const{return QSettings().value("proactive/dnd",false).toBool();}
int MorningLollipopModule::idleSeconds()const{
#ifdef Q_OS_WIN
LASTINPUTINFO i{sizeof(i)};return GetLastInputInfo(&i)?int((GetTickCount()-i.dwTime)/1000):0;
#else
return 0;
#endif
}
bool MorningLollipopModule::isFullScreenActive()const{
#ifdef Q_OS_WIN
HWND w=GetForegroundWindow();if(!w)return false;RECT a{};GetWindowRect(w,&a);HMONITOR m=MonitorFromWindow(w,MONITOR_DEFAULTTONEAREST);MONITORINFO i{sizeof(i)};GetMonitorInfo(m,&i);return a.left<=i.rcMonitor.left&&a.top<=i.rcMonitor.top&&a.right>=i.rcMonitor.right&&a.bottom>=i.rcMonitor.bottom;
#else
return false;
#endif
}
QString MorningLollipopModule::weatherDeliveryLine()const{if(m_weatherType=="rain")return "外面现在有雨，这颗糖的包装纸特意选了不怕潮的。出门的话记得看看伞在不在。";if(m_weatherType=="snow")return "外面在下雪，糖我先替你捂暖了一点点。";if(m_weatherType=="hot")return "今天有点热，我挑糖时差点把自己也塞进冰箱里。";if(m_weatherType=="cold")return "今天偏冷，这颗糖先放在手心里也能当一小会儿暖手糖。";if(m_weatherType=="clear")return "今天当地天气很晴朗，这颗糖在阳光下应该会亮一下。";if(m_weatherType=="cloudy")return "今天云有点多，我给糖纸留了一点亮色。";return {};}
void MorningLollipopModule::deliver(MorningLollipopRecord r,const QDateTime&now,bool test){if(r.greeting.isEmpty())r.greeting=offlineGreeting(r);r.weatherSnapshot=m_weatherText;r.greetingFingerprint=fingerprint(r.greeting);r.generationSource=r.generationSource.isEmpty()?"offline":r.generationSource;r.actualAt=now;r.viewed=false;const QString weatherLine=weatherDeliveryLine();const QString message=r.emoji+QStringLiteral(" ")+r.greeting+(weatherLine.isEmpty()?QString():QStringLiteral("\n")+weatherLine);if(isDnd()&&!test){r.status="stored_silent";r.delayReason="do_not_disturb";m_status="今天的棒棒糖已经安静地放进糖果罐。";}else{r.status="delivered";r.delayReason.clear();emit giftReady(QStringLiteral("Stellacandie 的晨间棒棒糖"),message);m_status="今天的棒棒糖已经送到啦，也看过当地天气了。";}m_storage->upsertMorningLollipop(r);refresh();emit changed();}
void MorningLollipopModule::evaluateNow(){if(!m_enabled||!m_storage)return;const auto now=QDateTime::currentDateTime();const bool weekend=now.date().dayOfWeek()>=6;const int start=weekend?m_weekendStart:m_workdayStart,end=weekend?m_weekendEnd:m_workdayEnd;const int minute=now.time().hour()*60+now.time().minute();auto r=m_storage->loadMorningLollipop(now.date());if(r.id==0){if(minute>end||minute>=720)return;setPickingStage("溜进糖果柜","我先看看今天哪一颗最合适……");r=createPlan(now);m_storage->upsertMorningLollipop(r);refresh();}if((r.status=="delivered"||r.status=="stored_silent"||r.status=="expired"))return;if(r.status=="planned"&&now.secsTo(r.plannedAt)<=3600)prepareGreeting(r);r=m_storage->loadMorningLollipop(now.date());if(now<r.plannedAt)return;if(minute>=720){r.status="expired";r.delayReason="missed_before_noon";m_storage->upsertMorningLollipop(r);refresh();return;}if(!m_city.isEmpty()&&r.delayReason!="refreshing_delivery_weather"&&(!m_lastWeatherSync.isValid()||m_lastWeatherSync.secsTo(now)>900)){refreshWeather();r.plannedAt=now.addSecs(90);r.delayReason="refreshing_delivery_weather";m_storage->upsertMorningLollipop(r);setPickingStage("最后看一眼窗外","我确认一下现在的天气，再把糖递给你。");return;}if(!m_storage->loadDueReminders(now.addSecs(600),10).isEmpty()){r.plannedAt=now.addSecs(720);r.delayReason="important_reminder";m_storage->upsertMorningLollipop(r);m_status="先把重要提醒让在前面，棒棒糖晚一点再来。";emit changed();return;}if(isFullScreenActive()||idleSeconds()>300){r.plannedAt=now.addSecs(isFullScreenActive()?600:300);r.delayReason=isFullScreenActive()?"fullscreen":"inactive";m_storage->upsertMorningLollipop(r);setPickingStage("藏在身后","等你忙完，我再拿出来。");return;}deliver(r,now);Q_UNUSED(start)}
void MorningLollipopModule::createTestGift(){auto r=createPlan(QDateTime::currentDateTime());r.giftDate=QDate::currentDate();r.plannedAt=QDateTime::currentDateTime();r.greeting=offlineGreeting(r);r.generationSource="offline_test";deliver(r,QDateTime::currentDateTime(),true);}
void MorningLollipopModule::refresh(){m_items=m_storage?m_storage->loadMorningLollipops():QList<MorningLollipopRecord>{};if(m_selected>=m_items.size())m_selected=qMax(0,m_items.size()-1);emit changed();}
QStringList MorningLollipopModule::items()const{QStringList out;for(const auto&r:m_items)out<<QStringLiteral("%1|%2|%3|%4|%5|%6").arg(r.giftDate.toString("yyyy-MM-dd"),r.emoji,r.flavorName,r.rarity,r.status,r.favorite?"favorite":"");return out;}
MorningLollipopRecord MorningLollipopModule::selected()const{return m_selected>=0&&m_selected<m_items.size()?m_items.at(m_selected):MorningLollipopRecord{};}
void MorningLollipopModule::select(int row){if(row<0||row>=m_items.size())return;m_selected=row;m_storage->markMorningLollipopViewed(m_items[row].id);refresh();m_selected=row;emit changed();}
void MorningLollipopModule::toggleFavorite(){auto r=selected();if(r.id>0){m_storage->setMorningLollipopFavorite(r.id,!r.favorite);refresh();}}
