#include "ReverseDiaryModule.h"
#include "../AiService.h"
#include "../data/DataRepository.h"
#include "../logic/DiaryStickerRole.h"
#include <QRegularExpression>
#include <QSettings>

ReverseDiaryModule::ReverseDiaryModule(DataRepository*s,AiService*a,QObject*p):FeatureModule(p),m_storage(s),m_ai(a){m_enabled=QSettings().value("modules/reverseDiaryEnabled",true).toBool();
    connect(a,&AiService::chatCompleted,this,[this](const QString&reply,const QString&,const QJsonObject&){if(!m_generating||m_ai->requestContext()!=QStringLiteral("reverse_diary"))return;const QDate target=m_targetDate;const bool automatic=m_automatic;m_generating=false;m_targetDate={};m_automatic=false;emit generatingChanged(false);const QString diary=sanitizeCompanionLanguage(reply);if(target.isValid()&&m_storage->saveDiaryEntry(target,diary)){ensureStickersForDate(target);if(automatic)QSettings().setValue("reverseDiary/lastAutomaticDate",target.toString(Qt::ISODate));emit diaryGenerated(diary);}else emit diaryFailed("日记生成成功，但写入数据库失败。");});
    connect(a,&AiService::chatFailed,this,[this](const QString&message){if(!m_generating||m_ai->requestContext()!=QStringLiteral("reverse_diary"))return;if(m_automatic)m_nextAutoRetry=QDateTime::currentDateTime().addSecs(600);m_generating=false;m_targetDate={};m_automatic=false;emit generatingChanged(false);emit diaryFailed(message);});
    m_autoTimer.setInterval(60000);connect(&m_autoTimer,&QTimer::timeout,this,&ReverseDiaryModule::evaluateAutoGeneration);m_autoTimer.start();QTimer::singleShot(5000,this,&ReverseDiaryModule::evaluateAutoGeneration);
}
QString ReverseDiaryModule::id()const{return "reverse_diary";}QString ReverseDiaryModule::displayName()const{return "反向日记";}bool ReverseDiaryModule::isEnabled()const{return m_enabled;}bool ReverseDiaryModule::isGenerating()const{return m_generating;}
void ReverseDiaryModule::setEnabled(bool v){if(v==m_enabled)return;m_enabled=v;QSettings().setValue("modules/reverseDiaryEnabled",v);emit enabledChanged(v);}
QString ReverseDiaryModule::sanitizeCompanionLanguage(QString c)const{c.remove(QRegularExpression(QStringLiteral("^\\s*[【\\[]?\\s*(?:反向日记模块(?:指令)?|日记模块(?:指令)?)\\s*[】\\]]?\\s*[:：]?\\s*")));c.remove(QRegularExpression(QStringLiteral("^\\s*\\d{4}[-/.年]\\d{1,2}[-/.月]\\d{1,2}日?\\s*[:：-]?\\s*")));c.replace("我的小主人","你");c.replace("小主人","你");c.replace("我的主人","你");c.replace("主人","你");c.replace("master","你",Qt::CaseInsensitive);c.replace("主仆","伙伴");return c.trimmed();}
bool ReverseDiaryModule::hasEntry(const QDate&d)const{for(const auto&e:m_storage->loadDiaryEntries())if(e.entryDate==d)return true;return false;}
void ReverseDiaryModule::ensureStickersForDate(const QDate&date){if(!m_storage->loadDiaryStickers(date).isEmpty())return;DreamRecord match;const DreamRecord*d=nullptr;for(const auto&x:m_storage->loadDreams(30))if(x.dreamDate==date){match=x;d=&match;break;}for(const auto&s:DiaryStickerRole::generate(date,m_storage->loadPetState(),d))m_storage->addDiarySticker(s);}
void ReverseDiaryModule::forceGenerate(){generateForDate(QDate::currentDate(),false);}
void ReverseDiaryModule::evaluateAutoGeneration(){if(!m_enabled||m_generating||!m_ai->isConfigured()||(m_nextAutoRetry.isValid()&&QDateTime::currentDateTime()<m_nextAutoRetry))return;const QDate target=QDate::currentDate().addDays(-1);if(target>=QDate(2025,1,1)&&!hasEntry(target))generateForDate(target,true);}
void ReverseDiaryModule::generateForDate(const QDate&target,bool automatic){if(!m_enabled||m_generating||!m_ai->isConfigured()||!target.isValid()||hasEntry(target)){if(!automatic)emit diaryFailed("日记模块未启用、正在生成、AI未配置，或者今天的日记已经存在。");return;}QList<ChatMessageRecord>history;for(const auto&m:m_storage->loadRecentMessages(200))if(m.createdAt.date()==target)history<<m;bool hasUser=false;for(const auto&m:history)if(m.sender=="user")hasUser=true;if(!hasUser&&!automatic){emit diaryFailed("今天还没有可以写进日记的聊天，先和精灵分享一点事情吧。");return;}if(!hasUser)history.append({0,"system",QStringLiteral("%1没有留下用户聊天。只能诚实写成安静、没有听到新故事的一天；禁止虚构用户做过的事、说过的话或见过的人。").arg(target.toString(Qt::ISODate)),QDateTime(target,QTime(23,59))});history.append({0,"user",QStringLiteral("请根据上面的真实聊天，以精灵第一人称写%1的日记。写出记住的具体事情、自己的感受和一个对明天的小期待。你和用户是平等的陪伴伙伴，绝对禁止称呼用户为主人、小主人、饲主或铲屎官。不要称呼自己为AI，不要分析或说教。没有聊天素材时诚实写那天很安静，禁止虚构用户事件。直接输出120到220字正文，不要标题、模块名、标签或复述指令。").arg(target.toString(Qt::ISODate)),QDateTime::currentDateTime()});m_targetDate=target;m_automatic=automatic;m_generating=true;emit generatingChanged(true);m_ai->sendChat(history,60,65,100,35,10,0,25,0,"reverse_diary");}
