#include "SummaryMagicModule.h"
#include "../AiService.h"
#include <QClipboard>
#include <QFile>
#include <QFileInfo>
#include <QGuiApplication>
#include <QJsonArray>
#include <QJsonObject>
#include <QLocale>
#include <QSettings>

SummaryMagicModule::SummaryMagicModule(DataRepository*s,AiService*ai,QObject*p):FeatureModule(p),m_storage(s),m_ai(ai){m_enabled=QSettings().value(QStringLiteral("modules/summaryMagicEnabled"),true).toBool();refreshHistory();m_phraseTimer.setInterval(6500);connect(&m_phraseTimer,&QTimer::timeout,this,[this]{static const QStringList phrases{QStringLiteral("唔……这一段好像很重要。"),QStringLiteral("等等，这几个概念得放在一起看。"),QStringLiteral("正在把绕来绕去的话压成知识小饼干……"),QStringLiteral("别催，知识魔法需要一点耐心！")};m_status=phrases.at(m_phraseIndex++%phrases.size());emit changed();});connect(ai,&AiService::summaryCompleted,this,[this](const QJsonObject&o){if(!m_busy)return;m_phraseTimer.stop();m_busy=false;m_resultText=formatResult(o);const QString title=o.value("title").toString().trimmed().isEmpty()?QStringLiteral("未命名总结"):o.value("title").toString().trimmed();if(m_storage)m_storage->addSummary(title,m_sourceName,m_mode,m_resultText);m_status=QStringLiteral("完成！快看看本喵抓得准不准。要不要顺便夸夸我？");refreshHistory();emit studyFinished(m_status);emit changed();});connect(ai,&AiService::summaryFailed,this,[this](const QString&e){if(!m_busy)return;m_phraseTimer.stop();m_busy=false;m_status=QStringLiteral("魔法刚才打了个喷嚏：%1").arg(e);emit changed();});}
void SummaryMagicModule::setEnabled(bool e){if(e==m_enabled)return;m_enabled=e;QSettings().setValue(QStringLiteral("modules/summaryMagicEnabled"),e);emit enabledChanged(e);emit changed();}
void SummaryMagicModule::refreshHistory(){if(!m_storage)return;const auto loaded=m_storage->loadSummaries();m_history.clear();m_history.reserve(loaded.size());for(const auto &item:loaded)m_history.append(item);}
QStringList SummaryMagicModule::historyItems()const{QStringList out;for(const auto&r:m_history)out<<QStringLiteral("%1|%2|%3|%4").arg(r.id).arg(r.createdAt.toString("MM-dd HH:mm"),r.title,r.sourceName);return out;}
bool SummaryMagicModule::loadFile(const QUrl&url){m_status.clear();const QString path=url.isLocalFile()?url.toLocalFile():url.toString();QFileInfo info(path);const QString ext=info.suffix().toLower();const QStringList allowed{"txt","md","log","csv","json","cpp","c","h","hpp","qml","py","js","ts","html","xml"};if(!info.exists()||!info.isFile()){m_status=QStringLiteral("请选择一个存在的普通文件。");emit changed();return false;}if(!allowed.contains(ext)){m_status=QStringLiteral("第一版支持 TXT、Markdown、代码、JSON、CSV、日志和HTML纯文本文件；PDF与Word将在后续加入解析器。");emit changed();return false;}if(info.size()>2LL*1024*1024){m_status=QStringLiteral("文件超过2 MB。请先截取需要总结的部分，避免一次发送过长内容。");emit changed();return false;}QFile file(path);if(!file.open(QIODevice::ReadOnly)){m_status=QStringLiteral("无法只读打开文件，可能正被其他程序占用。");emit changed();return false;}const QByteArray bytes=file.readAll();QString text=QString::fromUtf8(bytes);if(text.count(QChar::ReplacementCharacter)>qMax(2,text.size()/100))text=QString::fromLocal8Bit(bytes);if(text.trimmed().isEmpty()){m_status=QStringLiteral("文件中没有可总结的文字。");emit changed();return false;}m_sourceName=info.fileName();m_sourceInfo=QStringLiteral("%1 · %2 字符 · 只读").arg(QLocale().formattedDataSize(info.size())).arg(text.size());m_inputText=text.left(60000);if(text.size()>60000)m_status=QStringLiteral("原文较长，本次将总结前60000个字符。");emit changed();return true;}
void SummaryMagicModule::setInputText(const QString&t){const QString clipped=t.left(60000);const bool changedText=clipped!=m_inputText;m_inputText=clipped;if(changedText){m_sourceName=QStringLiteral("粘贴文本");m_sourceInfo=QStringLiteral("%1 字符").arg(m_inputText.size());}m_status=t.size()>60000?QStringLiteral("文本已截取到前60000个字符。"):QString();emit changed();}
void SummaryMagicModule::generate(const QString&mode,const QString&userInstruction){if(!m_enabled){m_status=QStringLiteral("总结魔法模块没有开启。");emit changed();return;}if(m_busy){return;}if(m_inputText.trimmed().size()<20){m_status=QStringLiteral("内容太短，还不足以施展总结魔法。");emit changed();return;}m_mode=QStringList{"brief","standard","study"}.contains(mode)?mode:QStringLiteral("standard");m_busy=true;m_phraseIndex=0;m_status=userInstruction.trimmed().isEmpty()?QStringLiteral("等等，交给本喵！眼镜戴好啦，我要认真读了。"):QStringLiteral("要求收到！本喵会照着你的重点认真翻书。");m_phraseTimer.start();emit studyStarted(m_status);emit changed();m_ai->summarizeText(m_inputText,m_mode,m_sourceName,userInstruction);}
QString SummaryMagicModule::formatResult(const QJsonObject&o)const{QString out=QStringLiteral("# %1\n\n%2").arg(o.value("title").toString(QStringLiteral("总结结果")),o.value("overview").toString());auto section=[&](const QString&title,const QJsonArray&a){if(a.isEmpty())return;out+=QStringLiteral("\n\n## %1\n").arg(title);for(const auto&v:a)out+=QStringLiteral("- %1\n").arg(v.toString());};section(QStringLiteral("核心要点"),o.value("key_points").toArray());section(QStringLiteral("行动事项"),o.value("action_items").toArray());section(QStringLiteral("复习问题"),o.value("review_questions").toArray());const QJsonArray keys=o.value("keywords").toArray();if(!keys.isEmpty()){QStringList list;for(const auto&v:keys)list<<v.toString();out+=QStringLiteral("\n\n关键词：%1").arg(list.join(QStringLiteral("、")));}return out.trimmed();}
void SummaryMagicModule::selectHistory(int row){if(row<0||row>=m_history.size())return;const auto&r=m_history.at(row);m_resultText=r.content;m_sourceName=r.sourceName;m_sourceInfo=QStringLiteral("历史总结 · %1").arg(r.createdAt.toString("yyyy-MM-dd HH:mm"));m_status.clear();emit changed();}
void SummaryMagicModule::deleteHistory(int row){if(row<0||row>=m_history.size()||!m_storage)return;if(m_storage->deleteSummary(m_history.at(row).id)){refreshHistory();emit changed();}}
void SummaryMagicModule::clear(){m_sourceName.clear();m_sourceInfo.clear();m_inputText.clear();m_resultText.clear();m_status.clear();emit changed();}
void SummaryMagicModule::copyResult(){if(!m_resultText.isEmpty())QGuiApplication::clipboard()->setText(m_resultText);m_status=QStringLiteral("总结已经复制到剪贴板。");emit changed();}
void SummaryMagicModule::setInteractionStatus(const QString&t){m_status=t;emit changed();}
void SummaryMagicModule::recordFeedback(const QString&kind){QSettings s;const QString key=QStringLiteral("summaryMagic/feedback/")+kind;s.setValue(key,s.value(key,0).toInt()+1);if(kind=="accurate")m_status=QStringLiteral("嘿嘿，看来本喵这次把重点抓得很稳！");else if(kind=="short")m_status=QStringLiteral("记下了，下次我会多保留一点上下文。");else if(kind=="verbose")m_status=QStringLiteral("收到，下次把魔法压得更紧凑一点。");else m_status=QStringLiteral("记下了，下次我会加强原文覆盖检查。");emit changed();}
