CREATE DATABASE IF NOT EXISTS emotion_sprite_sync CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'emotion_sync_migrator'@'%' IDENTIFIED BY 'REPLACE_MIGRATOR_PASSWORD' REQUIRE SSL;
CREATE USER IF NOT EXISTS 'emotion_sync_app'@'%' IDENTIFIED BY 'REPLACE_APP_PASSWORD' REQUIRE SSL;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, TRIGGER ON emotion_sprite_sync.* TO 'emotion_sync_migrator'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON emotion_sprite_sync.* TO 'emotion_sync_app'@'%';
FLUSH PRIVILEGES;
