#include "PetStateEngine.h"
#include <QRandomGenerator>
#include <algorithm>

PetStateEngine::PetStateEngine(PetStateRepository *storage,QObject *parent):QObject(parent),m_storage(storage){}
int PetStateEngine::mood()const{return m_state.mood;} int PetStateEngine::energy()const{return m_state.energy;}
int PetStateEngine::health()const{return m_state.health;} int PetStateEngine::closeness()const{return m_state.closeness;}
int PetStateEngine::boredom()const{return m_state.boredom;} int PetStateEngine::neglect()const{return m_state.neglect;}
int PetStateEngine::curiosity()const{return m_state.curiosity;} int PetStateEngine::irritation()const{return m_state.irritation;}
int PetStateEngine::fullness()const{return m_state.fullness;}
QString PetStateEngine::healthPhase()const{return m_state.healthPhase;}
QString PetStateEngine::healthPhaseName()const{if(m_state.healthPhase=="warning")return QStringLiteral("有点着凉");if(m_state.healthPhase=="sick")return QStringLiteral("魔法感冒");if(m_state.healthPhase=="recovering")return QStringLiteral("恢复中");return QStringLiteral("健康");}
QString PetStateEngine::conditionName()const{return m_state.condition=="magic_cold"?QStringLiteral("魔法感冒"):QStringLiteral("无");}
int PetStateEngine::recoveryProgress()const{return m_state.recoveryProgress;}
QString PetStateEngine::healthContext()const{return QStringLiteral("[HEALTH_CONTEXT] 精灵当前阶段=%1，状况=%2，健康=%3，恢复进度=%4。生病不是用户造成的，不许归责、威胁或索取补偿；精灵会自然恢复，用户分享故事、陪伴或让她休息只能温和加速恢复。").arg(m_state.healthPhase,conditionName()).arg(m_state.health).arg(m_state.recoveryProgress);}

void PetStateEngine::load(){m_state=m_storage->loadPetState();if(m_state.healthPhase.isEmpty())m_state.healthPhase="healthy";refreshForElapsedTime();m_resolvedState=resolveState();m_candidateState=m_resolvedState;}
int PetStateEngine::processMessage(const QString &message){const QString c=message.simplified();const bool mechanical=c==QStringLiteral("早上好")||c==QStringLiteral("中午好")||c==QStringLiteral("晚上好")||c==QStringLiteral("你好");m_state.energy-=1;if(mechanical){m_state.boredom+=4;m_state.irritation+=1;}m_state.neglect=std::max(0,m_state.neglect-2);m_state.lastInteraction=QDateTime::currentDateTime();if(m_state.healthPhase!="healthy")addRecovery(2);saveAndNotify();return publishResolvedState();}
int PetStateEngine::applySemanticEffect(const QJsonObject &effect){const int confidence=std::clamp(effect.value("confidence").toInt(80),0,100);const auto d=[&](const char*k,int lo,int hi){int v=std::clamp(effect.value(QLatin1String(k)).toInt(),lo,hi);return confidence<60?v/2:v;};m_state.mood+=d("mood",-6,6);m_state.energy+=d("energy",-4,3);m_state.closeness+=d("closeness",-1,1);m_state.boredom+=d("boredom",-6,6);m_state.curiosity+=d("curiosity",-6,6);m_state.irritation+=d("irritation",-6,6);if(m_state.healthPhase!="healthy")addRecovery(std::clamp(effect.value("care_recovery").toInt(),0,6));saveAndNotify();return publishResolvedState();}
int PetStateEngine::refreshForElapsedTime(){const QDateTime now=QDateTime::currentDateTime();updateHealthForElapsedTime(now);evaluateDailyIllness(now);if(!m_state.lastDigestionAt.isValid())m_state.lastDigestionAt=now;else{const qint64 hours=std::max<qint64>(0,m_state.lastDigestionAt.secsTo(now)/3600);if(hours>0){m_state.fullness-=std::min<qint64>(hours*3,60);m_state.lastDigestionAt=now;}}if(!m_state.lastInteraction.isValid())m_state.lastInteraction=now;else{const qint64 hours=std::max<qint64>(0,m_state.lastInteraction.secsTo(now)/3600);if(hours>=6){m_state.neglect+=std::min<qint64>(hours/3,25);m_state.boredom+=std::min<qint64>(hours/4,20);m_state.energy+=std::min<qint64>(hours/6,12);m_state.curiosity-=std::min<qint64>(hours/12,8);m_state.irritation-=std::min<qint64>(hours/4,15);if(hours>=24)m_state.mood-=std::min<qint64>(hours/12,12);m_state.lastInteraction=now;}}saveAndNotify();return resolveState();}
void PetStateEngine::adjustForDebug(const QString&s,int delta){if(s=="mood")m_state.mood+=delta;else if(s=="energy")m_state.energy+=delta;else if(s=="closeness")m_state.closeness+=delta;else if(s=="boredom")m_state.boredom+=delta;else if(s=="neglect")m_state.neglect+=delta;else if(s=="curiosity")m_state.curiosity+=delta;else if(s=="irritation")m_state.irritation+=delta;else if(s=="fullness")m_state.fullness+=delta;saveAndNotify();emit suggestedStateChanged(resolveState());}
void PetStateEngine::resetForDebug(){m_state=PetStateRecord{};m_state.health=100;m_state.lastInteraction=QDateTime::currentDateTime();saveAndNotify();emit suggestedStateChanged(resolveState());}
void PetStateEngine::forceMagicColdForDebug(){const auto now=QDateTime::currentDateTime();m_state.condition="magic_cold";m_state.lastIllness=now;m_state.illnessStartedAt=now;m_state.recoveryProgress=0;setHealthPhase("sick",now);saveAndNotify();m_resolvedState=10;emit suggestedStateChanged(10);}
void PetStateEngine::advanceRecoveryForDebug(int amount){addRecovery(std::clamp(amount,1,100));saveAndNotify();m_resolvedState=resolveState();emit suggestedStateChanged(m_resolvedState);}
void PetStateEngine::healForDebug(){m_state.condition.clear();m_state.recoveryProgress=0;setHealthPhase("healthy",QDateTime::currentDateTime());saveAndNotify();m_resolvedState=resolveState();emit suggestedStateChanged(m_resolvedState);}
void PetStateEngine::rest(){if(m_state.healthPhase!="healthy")addRecovery(8);m_state.energy+=8;saveAndNotify();emit suggestedStateChanged(resolveState());}
bool PetStateEngine::canEat(int nutrition,QString *reason){const int gain=std::clamp(nutrition*5,10,35);if(m_state.fullness>=90||m_state.fullness+gain>108){if(reason)*reason=QStringLiteral("我真的吃不下啦，先让我消化一会儿嘛。零食会好好留在袋子里的。");return false;}return true;}
void PetStateEngine::feedSnack(int nutrition){m_state.energy+=std::clamp(nutrition,1,8);m_state.fullness+=std::clamp(nutrition*5,10,35);m_state.lastDigestionAt=QDateTime::currentDateTime();m_state.mood+=2;m_state.boredom-=3;m_state.closeness+=1;saveAndNotify();m_resolvedState=resolveState();emit suggestedStateChanged(m_resolvedState);}
void PetStateEngine::setHealthPhase(const QString&p,const QDateTime&now){m_state.healthPhase=p;m_state.phaseChangedAt=now;updateHealthValue();}
void PetStateEngine::updateHealthValue(){if(m_state.healthPhase=="healthy")m_state.health=100;else if(m_state.healthPhase=="warning")m_state.health=75;else if(m_state.healthPhase=="sick")m_state.health=45+m_state.recoveryProgress/5;else m_state.health=70+m_state.recoveryProgress*3/10;}
void PetStateEngine::addRecovery(int amount){if(amount<=0||m_state.healthPhase=="healthy")return;m_state.recoveryProgress=std::clamp(m_state.recoveryProgress+amount,0,100);const auto now=QDateTime::currentDateTime();if(m_state.recoveryProgress>=100){if(m_state.healthPhase=="sick"||m_state.healthPhase=="warning"){m_state.recoveryProgress=0;setHealthPhase("recovering",now);}else{m_state.condition.clear();m_state.recoveryProgress=0;setHealthPhase("healthy",now);}}updateHealthValue();}
void PetStateEngine::updateHealthForElapsedTime(const QDateTime&now){if(m_state.healthPhase=="healthy")return;if(!m_state.phaseChangedAt.isValid())m_state.phaseChangedAt=now;const int hours=std::max<qint64>(0,m_state.phaseChangedAt.secsTo(now)/3600);if(hours<=0)return;if(m_state.healthPhase=="warning"&&hours>=3){m_state.recoveryProgress=0;setHealthPhase("sick",now);return;}addRecovery(hours*(m_state.healthPhase=="recovering"?18:3));m_state.phaseChangedAt=now;}
void PetStateEngine::evaluateDailyIllness(const QDateTime&now){if(m_state.healthPhase!="healthy"||m_state.lastIllnessCheckDate==now.date())return;m_state.lastIllnessCheckDate=now.date();if(m_state.lastIllness.isValid()&&m_state.lastIllness.daysTo(now)<7)return;int chance=3;if(m_state.energy<=25)chance+=4;if(m_state.neglect>=70)chance+=1;if(QRandomGenerator::global()->bounded(100)<std::min(chance,10)){m_state.condition="magic_cold";m_state.lastIllness=now;m_state.illnessStartedAt=now;m_state.recoveryProgress=0;setHealthPhase("warning",now);}}
int PetStateEngine::bounded(int v){return std::clamp(v,0,100);}void PetStateEngine::saveAndNotify(){m_state.mood=bounded(m_state.mood);m_state.energy=bounded(m_state.energy);m_state.closeness=bounded(m_state.closeness);m_state.boredom=bounded(m_state.boredom);m_state.neglect=bounded(m_state.neglect);m_state.curiosity=bounded(m_state.curiosity);m_state.irritation=bounded(m_state.irritation);m_state.fullness=bounded(m_state.fullness);updateHealthValue();m_storage->savePetState(m_state);emit statsChanged();}
int PetStateEngine::resolveState()const{if(m_state.healthPhase=="sick")return 10;if(m_state.healthPhase=="recovering")return 11;if(m_state.healthPhase=="warning")return 8;if(m_state.irritation>=70)return 4;if(m_state.irritation>=40)return 5;if(m_state.energy<=20)return 8;if(m_state.neglect>=70)return 5;if(m_state.curiosity>=65&&m_state.boredom<65)return 3;if(m_state.mood>=70&&m_state.energy>=35)return 2;if(m_state.boredom>=65)return 5;if(m_state.boredom>=35)return 0;return 1;}
int PetStateEngine::publishResolvedState(){const int c=resolveState();if(c==m_resolvedState){m_candidateState=c;m_candidateCount=0;return c;}if(c!=m_candidateState){m_candidateState=c;m_candidateCount=1;}else ++m_candidateCount;const bool urgent=c==4||c==8||c==10||c==11;if(urgent||m_candidateCount>=2){m_resolvedState=c;m_candidateCount=0;emit suggestedStateChanged(c);}return m_resolvedState;}
